version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secure_root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: secure_password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  users:
    image: 'epamhleblitvinau/users:1.0.0'
    container_name: 'users-i'
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_HOST: db
      MYSQL_PASSWORD: secure_root_password
    ports:
    - '8081:8080'
  posts:
    image: 'epamhleblitvinau/posts:1.0.0'
    container_name: 'posts-i'
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_HOST: db
      MYSQL_PASSWORD: secure_root_password
      USERS_URL: http://users:8080/users
    ports:
      - '8082:8080'
